<?php

namespace App;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-11-18 at 16:15:34.
 */
class CalculatorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Calculator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Calculator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers App\Calculator::add
     * @todo   Implement testAdd().
     */
    public function testAdd() {
        $this->assertEquals(4, $this->object->add(2, 2));
    }

}
